x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  init:
    restart: "no"
    build:
      context: ./init
      dockerfile: Dockerfile
    image: init:megaeth
    pull_policy: never
    environment:
      NETWORK: "${NETWORK}"
      MEGARETH_BOOTSTRAP_POLICY: "${MEGARETH_BOOTSTRAP_POLICY}"
      MEGARETH_ROLLUP_SEQUENCER: "${MEGARETH_ROLLUP_SEQUENCER}"
    volumes:
      - data:/data
      - ./private:/private
      - /etc/localtime:/etc/localtime:ro
    <<: *logging

  megaeth-node:
    depends_on:
      init:
        condition: service_completed_successfully
    image: ubuntu:24.04
    restart: unless-stopped
    env_file:
      - ./private/environment.sh
    ports:
      - "${P2P_PORT}:30305/tcp"
      - "${P2P_PORT}:30305/udp"
    volumes:
      - type: volume
        source: data
        target: /opt/megaeth/bin/rpc-node
        read_only: true
        volume:
          subpath: "snapshot/megaeth-rpc-v2.0.18/rpc-node-v2.0.18"

      - type: volume
        source: data
        target: /opt/megaeth/rpc-node/genesis.json:ro
        read_only: true
        volume:
          subpath: "snapshot/megaeth-rpc-v2.0.18/${NETWORK}/genesis.json"

      - type: volume
        source: data
        target: /opt/megaeth/rpc-node
        read_only: true
        volume:
          subpath: node

    command: /opt/megaeth/bin/rpc-node node
    labels:
      - traefik.enable=true
      - traefik.http.routers.${RPC_HOST:-megaeth}.service=${RPC_HOST:-megaeth}
      - traefik.http.routers.${RPC_HOST:-megaeth}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-megaeth}.rule=Host(`${RPC_HOST:-megaeth}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-megaeth}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-megaeth}lb.service=${RPC_HOST:-megaeth}
      - traefik.http.routers.${RPC_HOST:-megaeth}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-megaeth}lb.rule=Host(`${RPC_LB:-megaeth-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-megaeth}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-megaeth}.loadbalancer.server.port=${RPC_PORT:-9547}

      - traefik.http.routers.${WS_HOST:-megaethws}.service=${WS_HOST:-megaethws}
      - traefik.http.routers.${WS_HOST:-megaethws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-megaethws}.rule=Host(`${WS_HOST:-megaethws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-megaethws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-megaethws}lb.service=${WS_HOST:-megaethws}
      - traefik.http.routers.${WS_HOST:-megaethws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-megaethws}lb.rule=Host(`${WS_LB:-megaethws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-megaethws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-megaethws}.loadbalancer.server.port=${WS_PORT:-9548}

      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8002
      - metrics.network=${NETWORK:-}
    <<: *logging

volumes:
  data: